#-------------------------------------------
# Add yaml 
#packages:
#  mb60l: !include 
#    file: packages/Tuya_MB60L.yaml
#    vars:
#      blind_id: holl_l
#      tuya_mcu_rx: 20
#      tuya_mcu_tx: 21
#      open_weekends: 9
#      open_workday: 7
#      rotation: "Forbard" # "Reverse"
# and copy file esphome/packages/


  
#-------------------------------------------
# External_components:
#------------------------------------------- 
external_components:
  - source:
      type: local
      path: my_components
    components: [ tuya ]
    refresh: always   

#-------------------------------------------
# Uart
#------------------------------------------- 
uart:
  - id: uart_${blind_id}
    tx_pin: $tuya_mcu_tx
    rx_pin: $tuya_mcu_rx
    baud_rate: 9600

#-------------------------------------------
# Tuya
#------------------------------------------- 
tuya:
  - id: mcu_$blind_id
    uart_id: uart_${blind_id}

#-------------------------------------------
# Sensor
#------------------------------------------- 
sensor:
  - platform: "tuya"
    tuya_id: mcu_$blind_id
    sensor_datapoint: 19
    id: best_position_${blind_id}

#-------------------------------------------
# Switch
#------------------------------------------- 
switch:
  - platform: "tuya"
    tuya_id: mcu_$blind_id
    name: "CHILD LOCK${blind_id}"
    switch_datapoint: 101
    icon: "mdi:lock"
    entity_category: config

  - platform: "tuya"
    tuya_id: mcu_$blind_id
    id: tilt_mode_${blind_id}
   # name: tilt mode
    switch_datapoint: 103

#-------------------------------------------
# Select
#------------------------------------------- 
select:
  - platform: "tuya"
    tuya_id: mcu_$blind_id
    name: "Rotation ${blind_id}"
    id: rotation${blind_id}
    enum_datapoint: 11
 #   optimistic: true
    icon: "mdi:swap-horizontal"
    options:
      0: "Forbard"
      1: "Reverse"
    entity_category: config
    
  - platform: "tuya"
    tuya_id: mcu_$blind_id
    name: "Speed${blind_id}"
    enum_datapoint: 104
    optimistic: true
    options:
      0: "Low"
      1: "Medium"
      2: "Hight"
    entity_category: config
    icon: mdi:speedometer
    
  - platform: "tuya"
    tuya_id: mcu_$blind_id
    name: "Save pozition${blind_id}"
    enum_datapoint: 16
    optimistic: true
    options:
      0: "UP"
      1: "DOWN"
      2: "RESET"
    entity_category: config
    icon: mdi:content-save-all-outline
    
#-------------------------------------------
# Number
#------------------------------------------- 
number:
  - platform: "tuya"
    tuya_id: mcu_$blind_id
    name: "Best position${blind_id}"
    number_datapoint: 19
    min_value: 0
    max_value: 100
    step: 10
    entity_category: config
    icon: mdi:blinds-horizontal
    
#-------------------------------------------
# Cover
#------------------------------------------- 
cover:
  - platform: tuya
    name: "Motor${blind_id}"
    tuya_id: mcu_$blind_id
    id: cover_${blind_id}
    control_datapoint: 1
    position_datapoint: 9
    position_report_datapoint: 8
    direction_datapoint: 11
    restore_mode: NO_RESTORE
    min_value: 0
    max_value: 100
    device_class: blind
   
#-------------------------------------------
# Button
#------------------------------------------- 
button:
  - platform: template
    name: "Open tilt${blind_id}"   
    icon: mdi:blinds-horizontal-closed
    on_press: 
      then:
        - switch.turn_on: tilt_mode_${blind_id}
        - delay: 0.2s 
        - cover.open: cover_${blind_id}
        - delay: 1s 
        - switch.turn_off: tilt_mode_${blind_id}

  - platform: template
    name: "Close tilt${blind_id}"   
    icon: mdi:roller-shade-closed
    on_press: 
      then:
        - switch.turn_on: tilt_mode_${blind_id}
        - delay: 0.2s 
        - cover.close: cover_${blind_id}
        - delay: 1s 
        - switch.turn_off: tilt_mode_${blind_id}

  - platform: template
    name: "Open best position${blind_id}" 
    icon: mdi:roller-shade
    on_press: 
      then:
        - cover.control:
            id: cover_${blind_id}
            position: !lambda |- 
              return id(best_position_${blind_id}).state / 100;
  
#-------------------------------------------
#  BINARY_SENSOR
#-------------------------------------------   
binary_sensor:
  - id: !extend led_1
    on_press:
      then:
        - cover.close: cover_${blind_id}
  - id: !extend led_2
    on_press:
      then:
        - cover.close: cover_${blind_id}
        
#-------------------------------------------
# SUN 
#------------------------------------------- 
sun:
  id: sun_state
# Расвет
  on_sunrise:
    - if:
        condition:
          and: 
            - lambda: 'return id(sntp_time).now().hour >= $open_weekends;'
            - switch.is_on: morning_automation
        then:
          - cover.open: cover_${blind_id}
# Закат
  on_sunset:
    then:
      - cover.close: cover_${blind_id}
      
#-------------------------------------------
# TIME
#-------------------------------------------            
time:
  - id: !extend sntp_time
    on_time:
# workday 
      - hours: $open_workday
        minutes: '0'
        seconds: 0
        then:
          - if:
              condition:
                and:
                  - sun.is_above_horizon:
                  - binary_sensor.is_on: workday_sensor
                  - switch.is_on: morning_automation
              then:
                - cover.open: cover_${blind_id}
# weekends
      - hours: $open_weekends
        minutes: '0'
        seconds: 0
        then:
          - if:
              condition:
                - sun.is_above_horizon:
                - switch.is_on: morning_automation
              then:
                - cover.open: cover_${blind_id}   